apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
          env:
            - name: XPACK_MONITORING_ENABLED
              value: "false"
          envFrom:
            - configMapRef:
                name: kyripay-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: kibana
