spring:
  application:
    name: converter
  data:
    mongodb:
      database: converter
  cloud:
    stream:
      bindings:
        input:
          destination: converter-process
        output:
          destination: converter-notifications
      kafka:
        binder:
          brokers: ${KAFKA_HOST}
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST}:9090/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

