version: "3"
services:
  notification:
    image: ataliuk/notification
    container_name: notification-api
    environment:
      SPRING_DATA_MONGODB_HOST: notification-mongodb
    ports:
      - 8080:8080
  notification-mongodb:
    image: mongo:3.6
    container_name: notification-mongodb
    ports:
      - 27018:27017