apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: kyripay/payment-service
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: kyripay-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: ${POSTGRES_URL}/payments_ms?currentSchema=payments
