apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-server
          image: kyripay/eureka
          ports:
            - containerPort: 9090
