spring:
  # https://www.baeldung.com/spring-boot-h2-database
  datasource:
    url: jdbc:h2:mem:traces_db
    # sample for file-based db: url=jdbc:h2:file:/data/demo
    driver-class-name: org.h2.Driver
    # By default, Spring Boot configures the application to connect to an in-memory store with the username sa and an empty password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Consider using "create-drop" for "test" profile
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        # to make H2 console accessible when run in Docker container
        web-allow-others: true

  data:
    rest:
      base-path: /api
      # This BLOCKS my @RepositoryRestResource CRUD repo recognition for some reason. Got back to default. investigate.
      # detection-strategy: annotated
server:
  port: 8090
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: TRACE
    kyripay.traces: TRACE