version: "3"
services:
  converter:
    image: kyripay/converter
    container_name: converter
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      EUREKA_CLIENT_ENABLED: "false"
      KAFKA_HOST: kafka
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - kafka
  mongodb:
    image: mongo:3.6
    container_name: converter-mongodb
    ports:
      - 27017:27017
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
