version: "3"
services:
  converter:
    image: astankevich/kyripay-converter
    container_name: converter
  mongodb:
    image: mongo:3.6
    container_name: converter-mongodb
    ports:
      - 27017:27017
