apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: kyripay/apigateway
          ports:
            - containerPort: 9091
          env:
            - name: EUREKA_INSTANCE_PREFER-IP-ADDRESS
              value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
    - port: 9091
