apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: converter-mongodb
  template:
    metadata:
      name: converter-mongodb
      labels:
        app: converter-mongodb
    spec:
      containers:
        - name: converter-mongodb
          image: mongo:3.6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: converter-mongodb
spec:
  selector:
    app: converter-mongodb
  ports:
    - port: 27017
      targetPort: 27017
