apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
spec:
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: kyripay/converter
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb
            - name: KAFKA_HOST
              value: kafka-cluster
            - name: EUREKA_HOST
              value: eureka
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
