apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-server
          image: kyripay/eureka
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: 9090
      targetPort: 9090

