apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-server
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-cluster
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - port: 9092
