apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: notification-mongodb
  template:
    metadata:
      name: notification-mongodb
      labels:
        app: notification-mongodb
    spec:
      containers:
        - name: notification-mongodb
          image: mongo:3.6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: notification-mongodb
spec:
  selector:
    app: notification-mongodb
  ports:
    - port: 27017
      targetPort: 27018
