name: Converter service build
on:
  push:
    paths:
      - '.github/workflows/converter.yml'
      - 'converter_service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: '11.0.4'
      - name: Build and unit tests
        run: |
          cd converter_service
          ./gradlew build -x bootJar --info
      - name: Integration tests
        run: ./gradlew integrationTests --info
      - name: Contract tests
        run: ./gradlew contractTests --info
      - name: Api tests
        run: ./gradlew apiTests --info
      - name: Prepare documentation
        run: ./gradlew asciidoctor
      - name: Upload test results
        uses: actions/upload-artifact@master
        with:
          name: test-report
          path: build/reports/tests
      - name: Publish docker image
        run: ./gradlew dockerPushVersion -PcustomVersion=${{github.sha}}