name: Notification service build
on:
  push:
    paths:
      - '.github/workflows/notification.yml'
      - 'notification_service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: '11.0.4'
      - name: Build service, prepare bootJar and run unit tests
        run: |
          cd notification_service
          sh mvnw clean install
      - name: Run Integration tests
        run: |
          cd notification_service
          sh mvnw test -Pintegration
      - name: Run Api tests
        run: |
          cd notification_service
          sh mvnw test -Papi
      - name: Sonar analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd notification_service
          sh mvnw verify sonar:sonar \
               -Dsonar.projectKey=kyripay-notification \
               -Dsonar.organization=kyripay \
               -Dsonar.host.url=https://sonarcloud.io \
               -Dsonar.login=152498a6b1a5d9572033c6629b7f9cee2e76a5e3
      - name: Prepare Restdocs documentation
        run: |
          cd notification_service
          sh mvnw generate-resources -Prestdocs
      - name: Publish docker image
        run: |
          cd notification_service
          docker login --username kyripay --password "(VXB8Ehqp"
          sh mvnw dockerfile:build dockerfile:push -Pdocker