name: Payment service build
on:
  push:
    paths:
      - '.github/workflows/payment.yml'
      - 'payment_service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: '11.0.4'
      - name: Generate JOOQ sources
        run: |
          cd payment_service
          sh mvnw process-sources -Pgenerate-jooq-sources
      - name: Build service, prepare bootJar and run unit tests
        run: |
          cd payment_service
          sh mvnw install
      - name: Integration tests
        run: |
          cd payment_service
          sh mvnw test -Pintegration
      - name: Api tests
        run: |
          cd payment_service
          sh mvnw test -Papi
      - name: Sonar analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd payment_service
          sh mvnw verify sonar:sonar \
            -Dsonar.projectKey=kyripay_payment \
            -Dsonar.organization=kyripay \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=56a031546712293e238790d48b53ea92efedccce
      - name: Prepare Restdocs documentation
        run: |
          cd payment_service
          sh mvnw generate-resources -Prestdocs
      - name: Publish docker image
        run: |
          cd payment_service
          docker login --username kyripay --password "(VXB8Ehqp"
          sh mvnw dockerfile:build dockerfile:push -Pdocker